// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB5RK6IlMxOqJQFMzq9CMc25qctdMQSl0',
    appId: '1:434201058654:web:31f8e559265de9a01f83cf',
    messagingSenderId: '434201058654',
    projectId: 'eclass-b56fd',
    authDomain: 'eclass-b56fd.firebaseapp.com',
    storageBucket: 'eclass-b56fd.firebasestorage.app',
    measurementId: 'G-0LC33S6SYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpxQzn_Pg5VqDjVbXThA1o1eqOZ5fzRng',
    appId: '1:434201058654:android:40f7641c58be0ff21f83cf',
    messagingSenderId: '434201058654',
    projectId: 'eclass-b56fd',
    storageBucket: 'eclass-b56fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBexxAcg1vrm-_vjxwWJrqkAlljM3miv4Q',
    appId: '1:434201058654:ios:bb8b2d10169941e51f83cf',
    messagingSenderId: '434201058654',
    projectId: 'eclass-b56fd',
    storageBucket: 'eclass-b56fd.firebasestorage.app',
    iosBundleId: 'com.example.eclassFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBexxAcg1vrm-_vjxwWJrqkAlljM3miv4Q',
    appId: '1:434201058654:ios:bb8b2d10169941e51f83cf',
    messagingSenderId: '434201058654',
    projectId: 'eclass-b56fd',
    storageBucket: 'eclass-b56fd.firebasestorage.app',
    iosBundleId: 'com.example.eclassFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB5RK6IlMxOqJQFMzq9CMc25qctdMQSl0',
    appId: '1:434201058654:web:265021014f263e701f83cf',
    messagingSenderId: '434201058654',
    projectId: 'eclass-b56fd',
    authDomain: 'eclass-b56fd.firebaseapp.com',
    storageBucket: 'eclass-b56fd.firebasestorage.app',
    measurementId: 'G-YXMH2X4CJQ',
  );
}
